### ISSUE TITLE
Virtual address 65776f70

### ISSUE THREAD

**Issue by AlessioZanga** [pazos/android_kernel_samsung_goyawifi#1]
Hi, I've just compiled TWRP 2.8.5.0 recovery using your kernel source for SM-T110 device, but when I try to boot in recovery it gets stuck at Samsung's logo.
I've found in the log file this line:

...
[    0.693542] c0 1 (swapper/0) Unable to handle kernel paging request at virtual address 65776f70
[    0.693725] c0 1 (swapper/0) pgd = c0104000
[    0.693817] c0 1 (swapper/0) [65776f70] *pgd=00000000
[    0.694030] c0 1 (swapper/0) Internal error: Oops: 5 [#1] PREEMPT SMP ARM
...

The entire log is there: http://pastebin.com/M86DkfNi

Regards,
- Zalexx

**Comment by pazos** [comment]
Sorry, no info yet. I've managed to build a kernel that works on stock rom and currently I'm working on building CWM without bootloop.

Please check that your tree is updated because I've merged some wrong commits here (yesterday) which can crash your system - adding hotplug as default governor seems to be a bad idea ;(

**Comment by pazos** [comment]
Check new commits, use goyawifi_recovery_defconfig!
Sync omnirom 5.0 to build TWRP 2.8.5.0 and have luck; this is a kernel targeted for Jelly Bean!
